---
title: "About me!"
author: "Camila Maldonado"
date: "Last updated on `r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---

<!--
Comments in HTML are like this! 
-->

Maestro the master, Lucas Python. 

Hello! My name is Camila and I use she/her pronouns. I am currently a sophomore at Smith College where I double major in Education and Statistical and Data Sciences. I come from a small country located in the heart of south america, Paraguay. I am the oldest sister of a family of eight, and I have a dog called Titan! 

I am interested in finding opportunities where I can enhance my skills working on projects that can contribute to the common good. Previously, I have worked as an ESL teacher, an advisor for youth working on community projects, and on campus as teacher assistant and residence life in my college house. 
I am mostly going to post on this website my work in class and  outside of class. Some of this work, I have done in groups as well as some were done on my own. 
In my free time, you can find me biking around the Valley, going to the movies, or spending time with my sisters. 
This upcoming Spring semester, I will be taking an advance programming class using both R and Python as well as an introduction to Statistics and Probability, and Linear Algebra. 
If you would like to know more about my technical, feel free to check out my resume and my LinkedIn profile, or simply just contact me! 
I hope you enjoy my work, and let me know if you have any feedback. 





```{r, echo = FALSE}

```


